stages:
  - test
  - notify

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
  stage: test
  tags:
    - docker
  script:
    # install dependencies
    - npm ci
    # run Cypress tests
    - npx cypress run

  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/reports/html/index.html
      - cypress/reports/html/assets/
      - cypress/reports/html/videos/
      - variables.env
    expire_in: 1 day
    reports:
      dotenv: variables.env
  after_script:
    # Salvar o ID do job de testes em uma variável de ambiente
    - echo "TEST_JOB_ID=$CI_JOB_ID" > variables.env

notify-success:
  stage: notify
  needs: ["test"]
  tags: 
    - docker
  script:
    - apk add --no-cache curl grep
    - |
      # Carregar o ID do job de testes da variável de ambiente
      if [ -f variables.env ]; then
        source variables.env
      else
        echo "Arquivo variables.env não encontrado"
        exit 1
      fi
      REPORT_URL="https://git.esig.group/quarks/clinic/quarkclinic-e2e-tests/-/jobs/$TEST_JOB_ID/artifacts/raw/cypress/reports/html/index.html"
      curl -X POST -H "Content-Type: application/json" \
        -d "{
          \"text\": \"✅ *Testes bem-sucedidos no GitLab CI!*\\n\\n🔹 *Projeto:* $CI_PROJECT_NAME\\n🔹 *Branch:* $CI_COMMIT_BRANCH\\n🔹 *Baixar relatório:* <$REPORT_URL|Clique aqui para baixar o relatório>\\n🔹 *Ver mais detalhes:* $CI_PIPELINE_URL\"
        }" $GOOGLE_CHAT_WEBHOOK_URL
  when: on_success
  only:
    - main

notify-failure:
  stage: notify
  needs: ["test"]
  tags: 
    - docker
  script:
    - apk add --no-cache curl grep
    - |
      # Carregar o ID do job de testes da variável de ambiente
      if [ -f variables.env ]; then
        source variables.env
      else
        echo "Arquivo variables.env não encontrado"
        exit 1
      fi
      REPORT_URL="https://git.esig.group/quarks/clinic/quarkclinic-e2e-tests/-/jobs/$TEST_JOB_ID/artifacts/raw/cypress/reports/html/index.html"

      # Envia para o grupo Sprints
      curl -X POST -H "Content-Type: application/json" \
        -d "{
          \"text\": \"🚨 *Teste falhou no GitLab CI!*\\n\\n🔹 *Projeto:* $CI_PROJECT_NAME\\n🔹 *Branch:* $CI_COMMIT_BRANCH\\n🔹 *Baixar relatório:* <$REPORT_URL|Clique aqui para baixar o relatório>\\n🔹 *Ver mais detalhes:* $CI_PIPELINE_URL\"
        }" $GOOGLE_CHAT_WEBHOOK_URL

      # Envia para o grupo Pipeline
      curl -X POST -H "Content-Type: application/json" \
        -d "{
          \"text\": \"🚨 *Teste falhou no GitLab CI!*\\n\\n🔹 *Projeto:* $CI_PROJECT_NAME\\n🔹 *Branch:* $CI_COMMIT_BRANCH\\n🔹 *Baixar relatório:* <$REPORT_URL|Clique aqui para baixar o relatório>\\n🔹 *Ver mais detalhes:* $CI_PIPELINE_URL\"
        }" $GOOGLE_CHAT_QUARK_PIPELINE_PROD
  when: on_failure
  only:
    - main
